version: 2.1

working_dir: &working-dir
  working_directory: ~/baeharam/circleci-node-cache

node: &node
  <<: *working-dir
  executor:
    name: node/default


orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    <<: *node
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/baeharam/circleci-node-cache
          cache-path: ~/baeharam/circleci-node-cache
      - run:
          name: Build
          command: yarn build

workflows:
  version: 2
  common:
    jobs:
      - build
