version: 2.1

working_dir: &working-dir
  working_directory: ~/baeharam/circleci-node-cache

node: &node
  <<: *working-dir
  executor:
    name: node/default


orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    <<: *node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ./
      - run:
          name: Test timezone
          command: |
            yarn
            node ./src/index.js

workflows:
  version: 2
  common:
    jobs:
      - build
