version: 2.1

working_dir: &working-dir
  working_directory: ~/baeharam/circleci-node-cache

node: &node
  <<: *working-dir
  executor:
    name: node/default


orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    <<: *node
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/cache-path
      - run:
          name: Build
          command: yarn build

workflows:
  version: 2
  common:
    jobs:
      - build
